### ISSUE TITLE
Increased MIPS due to changes in PR #214

### ISSUE THREAD

**Issue by shuchitak** [xmos/sw_avona#238]
Changes in https://github.com/xmos/sw_avona/pull/214 seem to have increased MIPS for all modules. I first notice it in http://srv-bri-jcim0:8080/blue/organizations/jenkins/XMOS%2Fsw_avona/detail/develop/155/pipeline.
This PR contained changes to make sw_avona includable from an external project. I suspect some compile settings for modules have got modified as a result. Would need debugging.

**Comment by mbanth** [comment]
@shuchitak, is this issue specific to sw_avona or does it apply to the xCore SDK as a whole?

**Comment by shuchitak** [comment]
Hi @mbanth, all sw_avona modules now compile with -Os compiler flag irrespective of where they are included from. I haven't checked the compile options for any other modules outside of sw_avona that the xcore sdk might be including. I'm closing this issue since the increased mips seen in sw_avona profiling tests has been resolved as part of[ ](https://github.com/xmos/sw_avona/pull/243) merge
