### ISSUE TITLE
Integrate VNR model

### ISSUE THREAD

**Issue by mbanth** [xmos/sw_avona#248]
Add the VNR model into its destination repository. (AV2b)

**Comment by shuchitak** [comment]
@andrewdewhurst, could you explain this a bit more. Currently the tensorflow model is in py_vnr repo. The corresponding tflite model and the xcore optimised version of it is in the sw_avona repo as part of the sw_avona lib_vnr module. This makes the most sense to me. Could you let me know, which, if any of the models you want to move to xcore sdk repo? Thanks.

**Comment by mbanth** [comment]
@andrewdewhurst, is this issue still unresolved in your mind?

**Comment by mbanth** [comment]
@shuchitak, can you please provide information about the state of the documentation in this repository that covers the use of the xformer?

**Comment by shuchitak** [comment]
VNR model is integrated to lib_vnr and documented. All changes merged to develop.
