### ISSUE TITLE
Model maintenance and documentation

### ISSUE THREAD

**Issue by mbanth** [xmos/sw_avona#249]
Develop scripts to regenerate and retrain the model.  Provide documentation describing how to regenerate, retrain and, if necessary, re-integrate the model. (AV2b)

**Comment by shuchitak** [comment]
@andrewdewhurst, could you please explain this some more? The scripts to generate and train the model are in the python py_vnr repo. In sw_avona lib_vnr we use the xcore optimised version of the model in py_vnr. I'll add documentation about how to generate the xcore optimised model from the corresponding tflite one and integrate it to lib_vnr. Are you okay with this?

**Comment by andrewdewhurst** [comment]
@shuchitak sorry of this is confusing, as I appreciate there are several steps.  What I wanted was to be sure that:
1) Generate and train the model easily (scripted and documented) - I assume the O/P is TF
2) Convert TF to TFL (documented, probably keeping a script for this step too)
3) Process TFL model through xFormer tool -> which I think generates new TFLm flatbuffers (not sure how to doc/script)
4) Deploy the TFLm model which I assume requires a runtime component (which shold be in the SDK?)

**Comment by shuchitak** [comment]
Thanks @andrewdewhurst. From what I understand:
- 1 will be part of the py_vnr repo.
- I'm not sure about 2. I'll talk to @Allan-xmos and update this.
- 3 will involve documenting the steps required to get from the tflite model -> xcore optimised tflite model -> flatbuffers, similar to [https://github.com/xmos/xcore_sdk/blob/develop/examples/bare-metal/visual_wake_words/README.rst]

**Comment by mbanth** [comment]
We will discuss this issue at the 27 April 2022 Voice Pipeline Performance meeting to gain clarity about its scope and necessity.

**Comment by shuchitak** [comment]
As discussed in the 27 April 2022 Voice Pipeline Performance, py_vnr repo will contain the tf and tflite models, documentation regarding training, tf -> tflite conversion etc. accessible to anyone within XMOS.

tflite -> tflite micro conversion and beyond will be in sw_avona and will be demonstrated + documented in a VNR example in  avona, tracked in https://github.com/xmos/sw_avona/issues/267

**Comment by mbanth** [comment]
@andrewdewhurst, given the decisions taken at the 27 April 2022 Voice Pipeline Performance meeting and the existence of issue #267, is this issue complete?
