### ISSUE TITLE
Investigate open lib_aec issues for potential fixes in avona aec

### ISSUE THREAD

**Issue by shuchitak** [xmos/sw_avona#258]
- Understand if there's something in https://github.com/xmos/lib_aec/issues/191  and https://github.com/xmos/lib_aec/issues/188 that might warrant a change to the current test_aec_spec. 

- Look into https://github.com/xmos/lib_aec/issues/91 and https://github.com/xmos/lib_aec/issues/92 related to potential overflow in reference processing.
- Look into https://github.com/xmos/lib_aec/issues/67

Adding size label M since not sure of scope of this issue.

**Comment by mbanth** [comment]
@shuchitak, @hughh-xmos has said the lib_aec issues [91](https://github.com/xmos/lib_aec/issues/91) and [92](https://github.com/xmos/lib_aec/issues/92) have been fixed in the Python model, see his comment in each issue.
