### ISSUE TITLE
Extend pipeline examples to multi tile.

### ISSUE THREAD

**Issue by shuchitak** [xmos/sw_avona#281]
The pipeline examples currently have all components running on the same tile. The multi thread and single thread pipeline are using 446020 and 424884 bytes respectively, leaving 78268 bytes free in the worst case.

It'll be good to extend these to multi tile so that VNR and any future enhancements can be tested without risking running out of memory.

**Comment by shuchitak** [comment]
I've converted the multi thread avona example, avona_example_bare_metal_pipeline_multi_thread, to run across 2 tiles. The single thread pipeline example, avona_example_bare_metal_pipeline_single_thread cannot be converted since the entire pipeline is run as a set of functions called on one thread. Before making it multi tile, I'll have to make it multi threaded which would essentially make it the same as the multi thread example.

Options are -
- Remove single thread example and keep only the multi thread one.
- 

>

**Comment by mbanth** [comment]
@shuchitak, please provide the number of Story Points for this issue.  Thanks.

**Comment by shuchitak** [comment]
I've already provided 3 story points for this.

**Comment by shuchitak** [comment]
PR for this is merged to develop. Stage 1 runs on one tile and stages 2, 3 and 4 run on the other tile. I'm now able to integrate VNR into the pipeline.
