### ISSUE TITLE
Version mismatch error returned from inference_engine_load_model()

### ISSUE THREAD

**Issue by shuchitak** [xmos/sw_avona#282]
More details in this [JIRA](https://xmosjira.atlassian.net/browse/XT-205).

While we wait for the fix, the workaround is to change the versions in lib_tflite_micro/api/version.h  and lib_nn/api/version.h to match the ai-tools version. I'm going to be testing with this workaround when I work on integrating the latest model in py_vnr into sw_avona VNR module.

**Comment by mbanth** [comment]
We should have another issue to remove the workaround once the fix has been made.

**Comment by shuchitak** [comment]
I've updated sw_avona to use the latest model (https://github.com/xmos/sw_avona/issues/284) with this workaround in place. 
https://github.com/xmos/sw_avona/blob/develop/examples/bare-metal/shared_src/external_deps/fetch_deps.cmake#L24
https://github.com/xmos/sw_avona/blob/develop/examples/bare-metal/shared_src/external_deps/fetch_deps.cmake#L33

Will revert to using the xmos repos when this issue is fixed.

**Comment by shuchitak** [comment]
Merged https://github.com/xmos/sw_avona/pull/313

For future updates, as suggested by Deepak, When updating to a new xmos-ai-tools version, look in https://github.com/xmos/ai_tools/tree/v0.1.8/third_party for the lib_tflite_micro and lib_nn versions that need to be included in avona for the ai tools to be in sync with the runtime tflite.
