### ISSUE TITLE
Integrate latest VNR model

### ISSUE THREAD

**Issue by shuchitak** [xmos/sw_avona#284]
Integrate the VNR [model](https://github.com/xmos/py_vnr/tree/v0.1.0/model_output) released as part of py_vnr v0.1.0, into sw_avona VNR module. Will need workaround mentioned in https://github.com/xmos/sw_avona/issues/282 in order to test.

**Comment by mbanth** [comment]
@shuchitak, how much time do you think this issue will take to complete?  Can you please add a Size label and Story Points to indicate?  Thanks.

**Comment by mbanth** [comment]
@shuchitak, please provide the number of Story Points for this issue.  Thanks.

**Comment by shuchitak** [comment]
Story points are already added for this issue.

**Comment by shuchitak** [comment]
https://github.com/xmos/sw_avona/pull/283.

**Comment by shuchitak** [comment]
Pending:

- [ ] Clean up the [convert_model](https://github.com/shuchitak/sw_avona-1/blob/feature/latest_model/test/lib_vnr/test_wav_vnr/convert_model.py) script and document its usage.
- [ ] Move the model and convert_model script to a proper location out of the test_wav_vnr directory.

**Comment by shuchitak** [comment]
#283 is merged now. Documentation related things will be done as part of https://github.com/xmos/sw_avona/issues/297
