### ISSUE TITLE
Avona precision changes

### ISSUE THREAD

**Issue by uvvpavel** [xmos/sw_avona#285]
After talking to @shuchitak we decided to go through the whole repo to find where we could lose precision due to the wrong headroom calculation.

**Comment by mbanth** [comment]
@shuchitak and @uvvpavel, please update the Story Points field to state the number of engineering days you think this effort will take.  Thanks.

**Comment by shuchitak** [comment]
https://github.com/xmos/sw_avona/pull/290
Waiting on Jenkins

**Comment by shuchitak** [comment]
PR merged to develop
