### ISSUE TITLE
Identify core functions shared by AEC and IC

### ISSUE THREAD

**Issue by mbanth** [xmos/sw_avona#299]
Issue #292 discusses re-organising Avona DSP functionality to make functions currently residing in AEC but used by AEC and IC to reside in a common location rather than inside the AEC.  This issue exists to document which functions fall in the scope of this proposed re-organisation including any existing tests that will also move or need to be re-written.

**Comment by uvvpavel** [comment]
@Allan-xmos and I had a talk last week where we identified the list of lib_aec functions to transfer to adaptive filter infrastructure. They can be split into three groups.

IC uses directly from AEC (direct copy from lib_aec):
aec_priv_update_total_X_energy
aec_priv_update_X_fifo_and_calc_sigma_XX
aec_l2_calc_Error_and_Y_hat
aec_priv_create_output
aec_priv_calc_inv_X_energy
aec_priv_compute_T
aec_l2_adapt_plus_fft_gc

Both IC and AEC have (can be generalised):
update_X_fifo_1d

Not currently used by IC but @Allan-xmos wants to add it:
aec_priv_calc_delta
